apiVersion: v2
kind: Secret
metadata:
  name: "{{ .Release.Name }}-secret"
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.mariadb.db.user }}
  MYSQL_PASS: {{ .Values.mariadb.db.password }}
  MYSQL_HOST: {{ .Values.mariadb.db.host }}
  MYSQL_PORT: {{ .Values.mariadb.db.port}}
  MYSQL_DB: {{ .Values.mariadb.db.name }}
